name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup nix
      uses: cachix/install-nix-action@v22

    - name: Build
      run: nix develop --command nix build

    - name: Flake check 
      run: nix flake check --all-systems

    - name: Test
      run: nix develop --command go test -v ./...
